"""Templates module for AutoStack agents"""
from agents.templates.ci import get_workflow_content, WORKFLOW_TEMPLATES
from agents.templates.developer_pr import FEATURE_PR_BODY_TEMPLATE
from agents.templates.qa_pr import (
    TEST_RESULTS_TIMED_OUT_TEMPLATE,
    TEST_RESULTS_SUCCESS_TEMPLATE,
    TEST_RESULTS_FAILURE_HEADER_TEMPLATE,
    TEST_RESULTS_FAILURE_FOOTER_TEMPLATE,
    TEST_RESULTS_UNKNOWN_TEMPLATE,
    TEST_RESULTS_FOOTER,
    QA_REVIEW_HEADER,
    QA_REVIEW_QUALITY_LINE,
    QA_REVIEW_SECURITY_HEADER,
    QA_REVIEW_CODE_SMELLS_HEADER,
    QA_REVIEW_PERFORMANCE_HEADER,
    QA_REVIEW_SUGGESTIONS_HEADER,
    QA_REVIEW_FEEDBACK_HEADER,
    QA_REVIEW_FOOTER,
)
from agents.templates.documentation_pr import (
    DOC_COMMENT_HEADER,
    DOC_COMMENT_SUMMARY_LINE,
    DOC_COMMENT_FILES_HEADER,
    DOC_COMMENT_README_PREVIEW_HEADER,
    DOC_COMMENT_FOOTER,
)
