"""PR and Comment Templates for Developer Agent"""

FEATURE_PR_BODY_TEMPLATE = """## AutoStack Feature Implementation

**Feature**: {task_description}

**Implementation Details**:
- Generated by AutoStack Developer Agent
- Part of project: {project_id}
- Feature ID: {task_id}

**Files Changed**:
- TODO: List files that will be in this PR

**Testing Status**:
- Awaiting QA agent review and testing

**Merge Requirements**:
- Pass all automated checks
- Approval from QA agent
"""
