"""PR Comment Templates for Documentation Agent"""

# Documentation comment building blocks
DOC_COMMENT_HEADER = "## AutoStack Documentation\n"
DOC_COMMENT_SUMMARY_LINE = "**Summary:** {summary}\n"
DOC_COMMENT_FILES_HEADER = "\n### Generated Documentation Files"
DOC_COMMENT_README_PREVIEW_HEADER = "\n### README Preview"
DOC_COMMENT_FOOTER = "\n---\n*Generated by AutoStack Documentation Agent*"
