"""PR Comment Templates for QA Agent"""

TEST_RESULTS_TIMED_OUT_TEMPLATE = """## Test Execution Results

**Status:** Timed out waiting for results

**Reason:** {reason}

Tests have been committed to the PR. Check GitHub Actions manually for results.
"""

TEST_RESULTS_SUCCESS_TEMPLATE = """## Test Execution Results

**Status:** All tests passed!

**Language:** {language}
**Framework:** {test_framework}
**Workflow:** {workflow_name}

Tests have been committed to the PR and are ready for merge.

[View Details]({details_url})
"""

TEST_RESULTS_FAILURE_HEADER_TEMPLATE = """## Test Execution Results

**Status:** Some tests failed

**Language:** {language}
**Framework:** {test_framework}
**Workflow:** {workflow_name}

### Failed Checks:
"""

TEST_RESULTS_FAILURE_FOOTER_TEMPLATE = """

Tests have been committed to the PR. Please review the failures and fix them before merging.

[View Details]({details_url})
"""

TEST_RESULTS_UNKNOWN_TEMPLATE = """## Test Execution Results

**Status:** {conclusion}

**Language:** {language}
**Framework:** {test_framework}

Tests have been committed to the PR. Check GitHub Actions for details.

[View Details]({details_url})
"""

TEST_RESULTS_FOOTER = "\n---\n*Test execution performed by AutoStack QA Agent*"

# QA Review comment building blocks
QA_REVIEW_HEADER = "## AutoStack QA Review\n"
QA_REVIEW_QUALITY_LINE = "**Overall Quality:** {quality}\n"
QA_REVIEW_SECURITY_HEADER = "\n### Security Issues"
QA_REVIEW_CODE_SMELLS_HEADER = "\n### Code Smells"
QA_REVIEW_PERFORMANCE_HEADER = "\n### Performance Issues"
QA_REVIEW_SUGGESTIONS_HEADER = "\n### Suggestions"
QA_REVIEW_FEEDBACK_HEADER = "\n### Detailed Feedback"
QA_REVIEW_FOOTER = "\n---\n*Generated by AutoStack QA Agent*"
