"""replace_gcp_with_azure_settings

Revision ID: 6230bf3fb1d6
Revises: 005
Create Date: 2026-02-15 13:03:00.667304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6230bf3fb1d6'
down_revision = '005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logs_created_at'), table_name='logs')
    op.drop_index(op.f('ix_logs_level'), table_name='logs')
    op.drop_index(op.f('ix_logs_project_id'), table_name='logs')
    op.drop_index(op.f('ix_metrics_created_at'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_metric_type'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_project_id'), table_name='metrics')
    op.drop_index(op.f('ix_projects_created_at'), table_name='projects')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.add_column('system_settings', sa.Column('google_api_key', sa.Text(), nullable=True))
    op.add_column('system_settings', sa.Column('azure_subscription_id', sa.String(length=255), nullable=True))
    op.add_column('system_settings', sa.Column('azure_tenant_id', sa.String(length=255), nullable=True))
    op.add_column('system_settings', sa.Column('azure_client_id', sa.String(length=255), nullable=True))
    op.add_column('system_settings', sa.Column('azure_client_secret', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_tasks_agent_role'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_priority'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_workflow_states_phase'), table_name='workflow_states')
    op.drop_index(op.f('ix_workflow_states_project_id'), table_name='workflow_states')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_workflow_states_project_id'), 'workflow_states', ['project_id'], unique=False)
    op.create_index(op.f('ix_workflow_states_phase'), 'workflow_states', ['phase'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_tasks_priority'), 'tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_tasks_agent_role'), 'tasks', ['agent_role'], unique=False)
    op.drop_column('system_settings', 'azure_client_secret')
    op.drop_column('system_settings', 'azure_client_id')
    op.drop_column('system_settings', 'azure_tenant_id')
    op.drop_column('system_settings', 'azure_subscription_id')
    op.drop_column('system_settings', 'google_api_key')
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_index(op.f('ix_projects_created_at'), 'projects', ['created_at'], unique=False)
    op.create_index(op.f('ix_metrics_project_id'), 'metrics', ['project_id'], unique=False)
    op.create_index(op.f('ix_metrics_metric_type'), 'metrics', ['metric_type'], unique=False)
    op.create_index(op.f('ix_metrics_created_at'), 'metrics', ['created_at'], unique=False)
    op.create_index(op.f('ix_logs_project_id'), 'logs', ['project_id'], unique=False)
    op.create_index(op.f('ix_logs_level'), 'logs', ['level'], unique=False)
    op.create_index(op.f('ix_logs_created_at'), 'logs', ['created_at'], unique=False)
    # ### end Alembic commands ###
